print('SCHOOL BOOKSTORE')
print('--------------------------------------')
name = input('Enter your name: ')
majo = input('Enter your major: ')
grd = input('Enter your grade: ')
bok = input('Enter your book: ')
tim = input('Book use time: ')
cred = input('Enter your ID: ')
print('')
print('----------------------------------------------------')
print('{:20}{}'.format('Name: ' ,name))
print('{:20}{}'.format('Major: ' ,majo))
print('{:20}{}'.format('Grade: ' ,grd))
print('{:20}{}'.format('Book you took: ' ,bok))
print('------------------------------------------------------')
print('{:20}{}'.format('For: ' ,tim))
print('------------------------------------------------------')
print('{:20}{}'.format('ID: ' ,cred))